# Generated by Django 5.2.1 on 2025-05-30 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_id', models.CharField(db_column='MR_id', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(db_column='doctor_id', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='doctor_name', max_length=100)),
                ('specialization', models.CharField(db_column='specialization', max_length=100)),
                ('location_lat', models.FloatField(db_column='location_lat')),
                ('location_long', models.FloatField(db_column='location_lon')),
                ('available_from', models.TimeField(db_column='available_from')),
                ('available_to', models.TimeField(db_column='available_to')),
                ('visit_duration_mins', models.IntegerField(db_column='visit_duration_mins')),
                ('priority_score', models.IntegerField(db_column='priority_score')),
                ('others', models.TextField(db_column='others')),
                ('mr', models.ForeignKey(db_column='MR_id', on_delete=django.db.models.deletion.CASCADE, to='optimizer.mr')),
            ],
        ),
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='visit_reports/')),
                ('mr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_plans', to='optimizer.mr')),
            ],
        ),
        migrations.CreateModel(
            name='VisitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_order', models.PositiveIntegerField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.doctor')),
                ('visit_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='optimizer.visitplan')),
            ],
        ),
    ]
