# Generated by Django 5.2.1 on 2025-06-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('quantity', models.IntegerField()),
                ('est_value', models.FloatField()),
                ('impact_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('urgency', models.CharField(max_length=20)),
                ('voice_input', models.TextField()),
                ('suggested_action', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('voice_input', models.TextField()),
                ('reimbursement_pending', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutcomeCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('meaning', models.CharField(max_length=100)),
                ('mr_voice_equivalent', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='visitplan',
            name='mr',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='location_long',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='mr',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='others',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='priority_score',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='visit_duration_mins',
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mr',
            name='mr_id',
            field=models.CharField(db_column='MR_id', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('objective', models.TextField()),
                ('product', models.CharField(max_length=100)),
                ('voice_input', models.TextField()),
                ('auto_suggested', models.BooleanField(default=False)),
                ('mr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.mr')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_type', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('key_insight', models.TextField()),
                ('ai_interpretation', models.TextField()),
                ('follow_up', models.TextField()),
                ('next_step', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.doctor')),
                ('outcome_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.outcomecode')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.plan')),
            ],
        ),
        migrations.DeleteModel(
            name='VisitItem',
        ),
        migrations.DeleteModel(
            name='VisitPlan',
        ),
    ]
