# Generated by Django 5.2.1 on 2025-06-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_achievement_challenge_expense_outcomecode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='specialization',
        ),
    ]
