# Generated by Django 5.2.1 on 2025-06-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_rename_specialty_doctor_specialization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='PlantoMR',
        ),
        migrations.RenameModel(
            old_name='Visit',
            new_name='VisitRes',
        ),
    ]
