# Generated by Django 5.2.1 on 2025-06-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_rename_plan_plantomr_rename_visit_visitres'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plantomr',
            table='optimizer_plantoMR',
        ),
        migrations.AlterModelTable(
            name='visitres',
            table='optimizer_visitRes',
        ),
    ]
