# Generated by Django 5.2.1 on 2025-06-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0005_alter_plantomr_table_alter_visitres_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
    ]
