# Generated by Django 5.2.3 on 2025-06-27 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0006_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='suggested_action',
        ),
        migrations.RemoveField(
            model_name='visitres',
            name='plan',
        ),
        migrations.AddField(
            model_name='achievement',
            name='mr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.mr'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='voice_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='ai_suggested_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='mr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.mr'),
        ),
        migrations.AddField(
            model_name='expense',
            name='mr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.mr'),
        ),
        migrations.AddField(
            model_name='plantomr',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.doctor'),
        ),
        migrations.AddField(
            model_name='plantomr',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitres',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitres',
            name='mr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.mr'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='est_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='impact_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='urgency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='voice_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='voice_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantomr',
            name='mr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.mr'),
        ),
        migrations.AlterField(
            model_name='plantomr',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantomr',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantomr',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantomr',
            name='voice_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitres',
            name='ai_interpretation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitres',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.doctor'),
        ),
        migrations.AlterField(
            model_name='visitres',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitres',
            name='follow_up',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='visitres',
            name='key_insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitres',
            name='next_step',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitres',
            name='outcome_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.outcomecode'),
        ),
        migrations.AlterField(
            model_name='visitres',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitres',
            name='visit_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
