# Generated by Django 5.2.3 on 2025-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0007_remove_challenge_suggested_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
