# Generated by Django 5.2.3 on 2025-06-29 15:31

import django.db.models.fields.related
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0008_challenge_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice_assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_input', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='achievement',
            name='voice_input',
            field=models.TextField(blank=True, null=True, verbose_name=django.db.models.fields.related.ForeignKey),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='voice_input',
            field=models.TextField(blank=True, null=True, verbose_name=django.db.models.fields.related.ForeignKey),
        ),
        migrations.AlterField(
            model_name='expense',
            name='voice_input',
            field=models.TextField(blank=True, null=True, verbose_name=django.db.models.fields.related.ForeignKey),
        ),
        migrations.AlterField(
            model_name='plantomr',
            name='voice_input',
            field=models.TextField(blank=True, null=True, verbose_name=django.db.models.fields.related.ForeignKey),
        ),
    ]
