# Generated by Django 5.2.3 on 2025-07-01 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0010_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mr',
            options={'verbose_name': 'Medical Representative', 'verbose_name_plural': 'Medical Representatives'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='mr',
        ),
        migrations.AddField(
            model_name='mr',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mr',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mr_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='user',
            table='optimizer_user',
        ),
    ]
