# Generated by Django 5.2.3 on 2025-07-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0011_alter_mr_options_alter_user_options_remove_user_mr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
