# Generated by Django 5.2.3 on 2025-07-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0012_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
